Requires Cython to build.

libimagequant is included as git submodule. Before build do
$ git submodule init && git submodule update

If header file pngquant/lib/libimagequant.h changes significantly (build fails
with corresponding errors) then the autogenerated libimagequant.pxd file needs
to be updated:
   1. Install gccxml
   2. Download cwrap (git clone https://github.com/enthought/cwrap.git)
   3. run
         cd cwrap &&\
         python -c "from cwrap.config import Config, File;Config('gccxml', files=[File('../pngquant/lib/libimagequant.h')]).generate()" &&\
         mv _libimagequant.pxd ../imagequant/libimagequant.pxd &&\
         cd ..
   4. If build fails on callbacks definitions comment them out


